---

- name: Install Update CRON
  template:
    src="centos-mirror.j2"
    dest="{{ mirror_cron_dir }}/centos-mirror"
    owner="{{ mirror_unix_user }}"
    group="{{ mirror_unix_group }}"
    mode=0700

- name: Setup CRON Schedule
  cron:
    name="CentOS"
    minute="{{ centos_mirror_cron_minute }}"
    hour="{{ centos_mirror_cron_hour }}"
    user="{{ mirror_unix_user }}"
    state="present"
    job="{{ mirror_cron_dir }}/centos-mirror >/dev/null 2>&1"
    disabled="{{ centos_mirror_cron_disabled }}"
